resolver: lts-16.5

packages:
- hlist-attempt

ghc-options:
  # Disable partial type signature warnings because partial type
  # signatures are intentional in this repository.
  "$locals": -Wno-partial-type-signatures
